### ISSUE TITLE
我之前也见过类似的一个东西，他是将那些html代码绑定在这些组件的属性上，大神你是这样的？

### ISSUE THREAD

**Issue by 374046604** [jaweii/Vue-Layout#1]

**Comment by jaweii** [comment]
不是的，没有操作html
是把属性绑定到<my-component />上，然后用vue编译挂载上去
每次属性变动都重新编译

**Comment by lilili001** [comment]
大神 怎么把字符串模板传入vue的呢

**Comment by jaweii** [comment]
`new Vue({
    ...
    template:'<my-component />'
})`
