### ISSUE TITLE
是否需要使用vuex

### ISSUE THREAD

**Issue by sugang1990** [jaweii/Vue-Layout#11]
看了楼主的代码，使用了vuex,我在考虑是不是能够不使用vuex?
如果把属性面板和拖动后在画布生成的内容当成是一个组件，然后通过css样式，将属性面板移动到最左边，
而在属性面板那部分，使用v-model ，在生成的内容使用v-bind ，

**Comment by jaweii** [comment]
用vuex是为了解决跨组件通信，只要能解决，不用当然可以；
