### ISSUE TITLE
后端根据前端传过来的数据编译生成html页面具体是怎么实现的呢

### ISSUE THREAD

**Issue by gunnerofarsenal** [jaweii/Vue-Layout#12]

**Comment by jaweii** [comment]
没有用到服务端渲染。只是把用户的布局存储到了store里，在分享的时候，把store存储到了云端，在进入分享地址后，页面会读取云端的布局数据，然后存回到store里的components中，components的变动会触发预览视图的更新，然后得到了vue渲染后的html。
