### ISSUE TITLE
我想知道怎么将这些ui与后台联动呢

### ISSUE THREAD

**Issue by lbmjy0228** [jaweii/Vue-Layout#16]
这些页面可以通过组件搭建，但是都是死的，怎么与后台交互

**Comment by jaweii** [comment]
这个只能搭建ui，交互还是要开发者自己写。

**Comment by lbmjy0228** [comment]
您这边实现过把搭建ui的某些组件的数据接口暴露出来，然后进行与后台的绑定交互吗








2018年4月24日
-----------------------------------------------------------


在2018年4月24日 15:50，朱嘉伟<notifications@github.com> 写道：

Closed #16.

**Comment by jaweii** [comment]
绑定数据接口是可行的，但是我没有实现过，以后可能花时间来实现

**Comment by lbmjy0228** [comment]
感谢，目前还不知道怎么弄，我再研究下，期待您更新




    顺颂时祺！


在2018年4月24日 16:24，朱嘉伟<notifications@github.com> 写道：

绑定数据接口是可行的，但是我没有实现过，以后可能花时间来实现
