### ISSUE TITLE
Element-ui啥时候能支持？

### ISSUE THREAD

**Issue by danjiuruge** [jaweii/Vue-Layout#24]
您好，请问啥时候能支持Element-ui组件呢？

**Comment by jaweii** [comment]
目前项目停止维护了。
等我个人时间充沛后重构项目时，可能会有相关支持。

**Comment by xiaoai7904** [comment]
> 您好，请问啥时候能支持Element-ui组件呢？

https://github.com/xiaoai7904/web_designer
项目正在进行中...
欢迎提意见
