### ISSUE TITLE
整合一套UI组件工作量大概有多少

### ISSUE THREAD

**Issue by rhinonan** [jaweii/Vue-Layout#3]
如果将element-ui弄进来大概需要多少工作量，如果不大的话可以一起弄一下。

**Comment by MovBricks** [comment]
bootstrap的layoutit真的很好用，我最近也在思考怎么用可视化的方法解决VUE写界面的问题。我建议可以拉个群，一起讨论好好设计一下，把代码重构成可扩展UI库的。

**Comment by rhinonan** [comment]
@MovBricks 可以啊，拉个群呗~

**Comment by jaweii** [comment]
@rhinonan @MovBricks 可以一起做的~

拓展一个element的的tag标签组件，大概只需要3-5分钟，拓展一个table组件的话，可能就要很久了，而且似乎会碰到棘手的问题。

element的组件我几乎没用过，刚才看了下，比如element的图标是通过写class来设置图标的，`<i class="el-icon-edit"></i>`，Muse-UI的则是单独一个属性来控制图标，`<mu-icon value="home"/>`，那么在element-ui可视化的属性视图上，图标属性和class就混在一块了，所以对类似这部分的代码处理，会增加工作量。

我建了个QQ群205651189，你们加一下~

**Comment by lir9205** [comment]
请问element-ui整合有进展了吗
