### ISSUE TITLE
大神你好，你的框架支持阿里Weex的vue.js吗

### ISSUE THREAD

**Issue by songxing10000** [jaweii/Vue-Layout#6]

**Comment by jaweii** [comment]
你好
这个不是框架，这个是工具，它使开发者能更便捷的完成布局，并生成代码。
Weex的代码和vue是一样的，所以生成的代码在Weex中也应当能用。

**Comment by songxing10000** [comment]
@jaweii 但是右侧没有vue.js的选项啊

**Comment by jaweii** [comment]
不管你选的哪一个选项，生成的代码都是vue的代码，不存在vue.js选项这个说法的。
你只需要在你的vue项目里引入对应的ui，然后将生成的代码copy到你的页面，就可以了。
建议你找个UI的使用文档看看

**Comment by songxing10000** [comment]
厉害，我试试，一直做iOS对vue不太熟悉，见笑了
